### ISSUE TITLE
Data sharing among apps

### ISSUE THREAD

**Issue by 3dimaging** [upraneelnihar/streamlit-multiapps#1]
Hi,
This is a great adding to streamlit community. Thank you!
I have a question, how to share a dataset, for example, a pandas dataframe among the apps. One app/page will create a pandas dataframe, the second app/page will use the dataframe to do data analysis. Thank you, again!

**Comment by upraneelnihar** [comment]
hi, what you are asking is caching the data across various pages in the app.
One simple and  quick way of doing this is by writing the processed data frame from first page into a csv file and read this in the second page as the first step. Below is a small example of doing it. 

There might be a elegant way of doing this without using the csv write which i am not aware of at this moment.

1. Perform Preprocessing in page1 and store the processed file in processed.csv
```
# apps/page1.py

import streamlit as st
import pandas as pd
import numpy as np

def app():
    st.title('Page1')
    st.markdown('This page process the data and stores it in processed.csv')
    df_raw = pd.read_csv('raw.csv')
   
    ### perform processing and store it in processed.csv
    df_processed.to_csv('data/processed.csv', index=False)
```

2. Read the processed data frame in page2 and perform data analysis.
```
# apps/page2.py

import streamlit as st
import pandas as pd
import numpy as np

def app():
    st.title('Page2')
    st.markdown('This page loads the processed dataframe and performs data analysis.')
    df_processed = pd.read_csv('data/processed.csv')
    st.write(df_processed)
```

3. Create the main app
```
#app.py
from apps import (page1, page2) # import your app modules here

app = MultiApp()

# Add all your application here
app.add_app("Home", page1.app)
app.add_app("Analysis", page2.app)
```

4. Run the application
```
streamlit run app.py
```

**Comment by 3dimaging** [comment]
Thank you! The solution works for me.
